[project]
name = "ollivanders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.13.4",
    "pytest>=9.0.2",
    "pytest-sugar>=1.1.1",
]
